In [1]:
import numpy as np
import math
import time

In [2]:
#Zad1
'''Pacjenci w szpitalu otrzymują różne dawki leku w zależności od ich wagi.
 Stwórz funkcję, która przyjmuje listę wag pacjentów i zwraca listę z
 odpowiednimi dawkami leku.'''

def oblicz_dawki(wagi):
  dawki = []
  for waga in wagi:
    if waga < 50:
      dawka = 20
      dawki.append(dawka)
    elif waga >= 50 and waga <=100:
      dawka = 50
      dawki.append(dawka)
    else:
      dawka = 100
      dawki.append(dawka)
  return np.array(dawki)

wagi = np.array([45, 75, 105])
oblicz_dawki(wagi)

array([ 20,  50, 100])

In [4]:
#Zad2
'''W szpitalu prowadzone są badania dotyczące wpływu leku na ciśnienie krwi
 pacjentów. Dla listy pacjentów, która zawiera zapisane ciśnienie krwi przed
 i po podaniu leku, oblicz procent pacjentów, u których ciśnienie spadło po
 podaniu leku.'''

def lek(cisnienia):
  spadlo = 0
  for przed,po in cisnienia:
    if przed>po:
      spadlo += 1
  return spadlo*100/len(cisnienia)

cisnienia = [
    (120, 115),
    (140, 138),
    (130, 125),
    (150, 155),
    (110, 108)
]

print("Cisnienie spadło u  {:.0f} % pacjentów".format(lek(cisnienia)))

Cisnienie spadło u  80 % pacjentów


In [ ]:
#Zad6 obliczanie bledu maszynowego float16

def calculate_machine_epsilon_f16():
  epsilon = np.float16(1.0)
  #dzieli epsilon na pół dopóki nie jest nieznaczący
  while np.float16(1+epsilon) != np.float16(1.0):
    epsilon = epsilon/np.float16(2.0)
  return epsilon

print(calculate_machine_epsilon_f16())

0.0004883


In [5]:
#Zad3
'''W dziedzinie medycyny obrazowej często stosuje się przekształcenia obrazów.
 Jednym z najprostszych z nich jest progowanie (thresholding). Polega ono na
 porównywaniu wartości danego piksela z wartością progową i wpisywanie do niego
 wartości 255 jeśli jest większy od wartości progowej lub 0 jeśli jest mniejszy.
 Funkcja thresholding, przyjmuje dwuwymiarową macierz (obraz) oraz wartość
 progową T i zwraca nową macierz po operacji thresholdingu.'''

def tresholding(obraz, T):
  for i in range(len(obraz)):
    for j in range(len(obraz[0])):
      if obraz[i][j] < T:
        obraz[i][j]=0
      else:
        obraz[i][j]=255
  return obraz

obraz = np.array([
    [120, 130, 140],
    [150, 160, 170],
    [180, 190, 200]
])
tresholding(obraz, 150)

array([[  0,   0,   0],
       [255, 255, 255],
       [255, 255, 255]])

In [6]:
#Zad4
'''Dane z EEG (elektroencefalografia) pacjenta są zapisane w postaci tablicy
 numpy reprezentującej napięcie zarejestrowane w kolejnych punktach czasowych.
 Chcielibyśmy analizować te dane w segmentach o określonej długości czasu (tzw.
 okna czasowe). Napisz generator, który będzie zwracać fragmenty tej tablicy.'''

def generator_segmentow_eeg(eeg_data, segment_length):
  i=0
  while i <= len(eeg_data):
    yield eeg_data[i:i+segment_length]
    i+=segment_length

eeg_data = np.array([0.5, 0.6, 0.7, 0.55, 0.65, 0.7, 0.8, 0.85])
gen = generator_segmentow_eeg(eeg_data, 3)
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))

[0.5 0.6 0.7]
[0.55 0.65 0.7 ]
[0.8  0.85]


StopIteration: 

In [7]:
#Zad5

def universal_calculator(*args, **kwargs):
  if kwargs["operation"] == "add":
    wynik = 0
    for wartosc in args:
      wynik += wartosc
  if kwargs["operation"] == "multiply":
    wynik = 1
    for wartosc in args:
      wynik *= wartosc
  if kwargs["operation"] == "divide":
    wynik = args[0]
    args_list = list(args)
    args_list.pop(0)
    for wartosc in args_list:
      wynik /= wartosc
  if kwargs["operation"] == "substract":
    wynik = 0
    for wartosc in args:
      wynik -= wartosc

  if "power" in kwargs.keys():
    wynik = wynik ** kwargs["power"]

  if "show_steps" in kwargs.keys():
    dzialania = {"add": "+", "multiply": "*", "substract":"-", "divide":"/"}
    steps = ""
    for x in args:
      steps += str(x)
      steps += dzialania[kwargs["operation"]]
    steps = steps[:-1] + "="
    steps += str(wynik)
    print(steps)

  return wynik

print(universal_calculator(1, 2, 3, 4, operation="add"))
print(universal_calculator(1, 2, 3, operation="multiply"))
print(universal_calculator(1, 3, operation="divide"))
print(universal_calculator(10, 2, operation="divide", power=2))
print(universal_calculator(1, 2, 3, operation="add", show_steps=True))

10
6
0.3333333333333333
25.0
1+2+3=6
6


In [8]:
#Zad7
'''Porównanie numpy do tablicy tradycyjnej'''

# Tworzymy listę wartości od 0 do 10^6
values = [i * 0.001 for i in range(1000000)]

start_time = time.time()

sin_values = []
for val in values:
    sin_values.append(math.sin(val))

end_time = time.time()
print(f"Traditional loop took {end_time - start_time} seconds")

start_time = time.time()

sin_values = np.zeros_like(values)
# for val in values:
#     sin_values.append(np.sin(val))
for i in range(len(values)):
    sin_values[i] = np.sin(values[i])

end_time = time.time()
print(f"Numpy loop took {end_time - start_time} seconds")

Traditional loop took 0.42354846000671387 seconds
Numpy loop took 1.90628981590271 seconds


In [ ]:
#Zad8
'''Twoim zadaniem jest stworzenie prostego kalkulatora oszczędnościowego,
 który pomoże użytkownikowi przewidzieć, ile pieniędzy uda mu się zaoszczędzić
 w ciągu określonego czasu.'''

P = float(input("Podaj początkową sumę oszczędności: "))
PMT = float(input("Podaj miesięczną kwotę, którą planujesz oszczędzać: "))
r = float(input("Podaj roczne oprocentowanie swojego konta oszczędnościowego [%]: "))/100
t = int(input("Podaj liczbę lat, przez które planujesz oszczędzać: "))
n=12

#Końcowa suma obliczana według podanego wzoru
A = (P*((1+r/n)**(n*t)))+(PMT*( (((1+r/n)**(n*t))-1)/(r/n) ))
print("\nKońcowa suma oszczędności: {:.2f}".format(A))

Podaj początkową sumę oszczędności: 0
Podaj miesięczną kwotę, którą planujesz oszczędzać: 500
Podaj roczne oprocentowanie swojego konta oszczędnościowego [%]: 3
Podaj liczbę lat, przez które planujesz oszczędzać: 5

Końcowa suma oszczędności: 32323.36
