In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
#Zad1
'''Napisz funkcję implementującą algorytm eliminacji Gaussa dla dowolnej macierzy
kwadratowej, którą można sprowadzić do postaci górnej trójkątnej. Przetestuj
funkcję dla różnych macierzy (w tym dla macierzy o dużym rozmiarze). Pamiętaj o
poprawnej implementacji pivotów.'''

def gaussian_elimination(A : np.ndarray):
    """
    A - input matrix (2-D, np.ndarray)
    """
    n=len(A)
    U=A.copy().astype(float)
    L=np.identity(n)

    for k in range(len(A)-1):
        max_ind = np.argmax(np.abs(U[k:n,k])) + k
        #pivoting
        U[ [k,max_ind], k:n ] = U[ [max_ind,k], k:n ]
        L[ [k,max_ind], :k ] = L[ [max_ind,k], :k ]

        for j in range(k+1, n):
            L[j,k] = U[j,k] / U[k,k]
            pom = U[j,k:n] - L[j,k]*U[k,k:n]
            U[j,k:n] = pom

    return U, L  #U-upper, L-lower triangular matrix

A=np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])
print('macierz A:')
print(A)
Ua, La = gaussian_elimination(A)
print('macierz Ua:')
print(Ua)
print('macierz B:')
B = np.random.randint(0, 10, size=(10, 10))
print(B)
Ub, Lb = gaussian_elimination(B)
print('macierz Ub:')
print(Ub)

macierz A:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]
macierz Ua:
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
macierz B:
[[8 0 1 9 9 6 3 6 2 7]
 [5 3 1 8 0 6 7 8 9 5]
 [3 0 1 4 8 7 3 1 0 5]
 [3 0 5 1 7 0 2 8 5 1]
 [0 1 8 4 9 3 0 3 3 5]
 [0 3 0 5 9 6 3 8 6 1]
 [7 4 4 7 5 2 6 0 4 7]
 [4 4 9 0 4 2 8 8 0 4]
 [1 9 2 1 8 4 7 5 6 3]
 [0 0 8 6 6 0 7 3 2 5]]
macierz Ub:
[[ 8.00000000e+00  0.00000000e+00  1.00000000e+00  9.00000000e+00
   9.00000000e+00  6.00000000e+00  3.00000000e+00  6.00000000e+00
   2.00000000e+00  7.00000000e+00]
 [ 0.00000000e+00  9.00000000e+00  1.87500000e+00 -1.25000000e-01
   6.87500000e+00  3.25000000e+00  6.62500000e+00  4.25000000e+00
   5.75000000e+00  2.12500000e+00]
 [ 0.00000000e+00  0.00000000e+00  8.00000000e+00  6.00000000e+00
   6.00000000e+00  0.00000000e+00  7.00000000e+00  3.00000000e+00
   2.00

In [8]:
#Zad2
'''Korzystając z funkcji zaimplementowanej w Zadaniu 1 - zaimplementuj funkcję
do rozwiązywania układów równań (zakładając, że układ równań jest oznaczony).
Skorzystaj z funkcji "solve upper triangular" zaimplementowanej na zajęciach.'''

def solve_upper_triangular(A : np.ndarray, y : np.ndarray):
    x = np.zeros_like(y).astype(float)
    #iterate backward
    for i in range(A.shape[0] - 1, -1, -1):
        if i == A.shape[0] - 1:
            x[i] = y[i] / A[i,i]
        else:
            x[i] = (y[i] - np.sum(A[i, i+1:] @ x[i+1:]) ) / A[i, i]
    return x

def solve_equation(A : np.ndarray, y : np.ndarray):
    """
    A - input matrix (2-D, np.ndarray)
    y - coefficients (1-D, np.ndarray)
    return x, where Ax = y
    """
    U, L = gaussian_elimination(A)
    x = solve_upper_triangular(U, y)
    return x

A = np.array([
    [2, 4, 1],
    [0, 1, 3],
    [0, 0, 2]
])
y = np.array([7, 4, 2])

x = solve_equation(A, y)
print(x)

[1. 1. 1.]


In [9]:
#Zad3
'''Bazując na funkcji "solve_upper_triangular" zaimplementuj funkcję
"solve_lower_triangular", a następnie wykorzystaj ją do rozwiązania
przykładowych układów równań korzystając z dekompozycji LU'''

def solve_lower_triangular(A : np.ndarray, y : np.ndarray):
    """
    A - input matrix (2-D, np.ndarray)
    y - coefficients (1-D, np.ndarray)
    return x, where Ax = y
    """
    x = np.zeros_like(y).astype(float)
    for i in range(A.shape[0]):
        if i == 0:
            x[i] = y[i] / A[i,i]
        else:
            x[i] = (y[i] - np.sum(A[i, :i+1] @ x[:i+1])) / A[i, i]
    return x


# Use the "solve_lower_triangular", "solve_upper_triangular" and the LU decomposition
# to solve a chosen set of equations (with a single solution).

#AX = B
A = np.array([
    [2, 4, 1],
    [0, 1, 3],
    [0, 0, 2]
])
B = np.array([7, 4, 2])

U, L = gaussian_elimination(A)

D = solve_lower_triangular(L, B)
X = solve_upper_triangular(U, D)
print(X)

[1. 1. 1.]
